const yy = {
  _id: "5e68213734031300172236b0",
  courses: ["אופנה", "אדריכלות", "אופטיקה", "אינטרנט", "איפור", "מתמטיקה"],
  studyCities: [
    "אבו סנאן",
    "אבו ג'ווייעד",
    "אבו גוש",
    "אבו סריחאן",
    "אבו עבדון",
    "אבו עמאר",
  ],
  rating: 0,
  fullName: "איתי פרץ מורה",
  phone: "0547107691",
  priceAtStudent: 150,
  price: 100,
  gender: "זכר",
  city: "אבו סנאן",
  university: "הקריה להנדסאים",
  generalDescription: "מורה מצויין עם יותר מ200 שנות נסיון ",
  availablesDays: ["שלישי", "שני"],
  avaiablesHours: ["20", "21", "22"],
  age: "11/03/2020",
  profile: "teacher",
  email: "peretz.itay@info.cts.org.il",
  views: 39,
  __v: 0,
  pic: "https://i.imgur.com/tP6r2mx.jpg",
};
